version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    cooldown:
      default-days: 7
    commit-message:
      prefix: "actions: "
    groups:
      ci-deps:
        patterns:
          - "*"
  - package-ecosystem: "nuget"
    directories:
      # XenClean references EarlyInitNAOT, which Dependabot cannot parse.
      # For some reason, exclude-paths doesn't work for this purpose. So we have to exclude that manually.
      - "/DriverInstallCustomAction"
      - "/HlkxSigner"
      - "/InstallerTests"
      - "/XenDriverUtils"
      - "/xenplus"
      - "/xenplus_lib"
      - "/xenplus_session"
      - "/xenplus_tests"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 15
    ignore:
      - dependency-name: "WixToolset.*"
