version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 15
    groups:
      trusted:
        patterns:
          - "actions/*"
  - package-ecosystem: "nuget"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 15
    ignore:
      - dependency-name: "WixToolset.*"
