<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <Platforms>x64;x86;ARM64</Platforms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AccelerateBuildsInVisualStudio>false</AccelerateBuildsInVisualStudio>
    <SupportedOSPlatformVersion>10.0.14393.0</SupportedOSPlatformVersion>

    <!-- Native AOT -->
    <PublishAot>true</PublishAot>
    <PublishTrimmed>true</PublishTrimmed>
    <IsAotCompatible>true</IsAotCompatible>
    <TrimmerSingleWarn>false</TrimmerSingleWarn>

    <!-- mitigations -->
    <ControlFlowGuard>Guard</ControlFlowGuard>
    <CetCompat>true</CetCompat>

    <!-- feature/size options -->
    <InvariantGlobalization>true</InvariantGlobalization>
    <UseSystemResourceKeys>true</UseSystemResourceKeys>
    <OptimizationPreference>Size</OptimizationPreference>

    <!-- versioning -->
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateSupportedRuntime>false</GenerateSupportedRuntime>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <LinkerArg Include="/DEPENDENTLOADFLAG:0x800" Condition="$(RuntimeIdentifier.StartsWith('win'))" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\XenDriverUtils\XenDriverUtils.csproj" />
  </ItemGroup>

  <Target Name="XenGeneratedFiles" BeforeTargets="BeforeBuild">
    <Exec Command="$(SystemRoot)\System32\WindowsPowerShell\v1.0\powershell.exe -noprofile -noninteractive -executionpolicy bypass $(ProjectDir)scripts\genfiles.ps1 -ProjectDir $(ProjectDir)" />
    <ItemGroup>
      <Compile Remove="Branding.cs" />
      <Compile Include="Branding.cs" />
    </ItemGroup>
  </Target>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="$(SystemRoot)\System32\WindowsPowerShell\v1.0\powershell.exe -noprofile -noninteractive -executionpolicy bypass $(ProjectDir)scripts\sign.ps1 -ProjectDir $(ProjectDir) -Configuration $(Configuration) -Platform $(Platform)" />
  </Target>

</Project>
