name: Attest artifact

on:
  workflow_call:
    inputs:
      subject-name:
        required: true
        type: string
      subject-digest:
        required: true
        type: string
      catalog-name:
        required: false
        type: string

permissions:
  id-token: write
  contents: read
  attestations: write

jobs:
  attest:
    runs-on: ubuntu-latest
    steps:
      - name: Attest artifact
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{inputs.subject-name}}
          subject-digest: ${{inputs.subject-digest}}
      - name: Download catalog
        if: ${{inputs.catalog-name != ''}}
        uses: actions/download-artifact@v4
        with:
          path: catalog/
          name: ${{inputs.catalog-name}}
      - name: Attest catalog
        if: ${{inputs.catalog-name != ''}}
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: catalog/${{inputs.catalog-name}}.csv
