name: build-xstdvga

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-xstdvga:
    runs-on: windows-2022
    env:
      WINPV_OUTPUT: xstdvga/vs2022/x64/Release/xstdvga
      WINPV_CATALOG: catalog.csv
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
      - name: Add MSBuild
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0
      - name: Add CodeQL
        id: add_codeql
        uses: github/codeql-action/init@9e907b5e64f6b83e7804b09294d44122997950d6 # v4.32.3
        with:
          build-mode: none
      - name: Add CodeQL to PATH
        run: Resolve-Path "${{steps.add_codeql.outputs.codeql-path}}\.." | Add-Content -Path $Env:GITHUB_PATH -Force
      - name: Download packs
        run: |
          codeql pack download microsoft/windows-drivers@1.8.2 microsoft/cpp-queries@0.0.4
          if ($LASTEXITCODE -ne 0) {
            throw "CodeQL download failed with error $LASTEXITCODE"
          }
      - name: Configure branding
        uses: ./.github/actions/branding
        with:
          branding-data: ${{toJson(vars)}}
      - name: Build xstdvga
        run: .\build-xstdvga.ps1 -Configuration Release -Platform x64
      - name: Catalog xstdvga
        run: |
          Import-Module .\scripts\artifact.psm1 -Force
          Get-ArtifactCatalog -Path .\$Env:WINPV_OUTPUT -Include *.sys, *.inf |
          Export-Csv -NoTypeInformation .\$Env:WINPV_OUTPUT\$Env:WINPV_CATALOG
      - name: Upload xstdvga
        id: upload
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          path: ${{env.WINPV_OUTPUT}}/
          name: xstdvga
    outputs:
      output-path: ${{env.WINPV_OUTPUT}}
      output-sha256: ${{steps.upload.outputs.artifact-digest}}
      catalog-name: ${{env.WINPV_CATALOG}}
