name: build-drivers

on:
  workflow_call:

jobs:
  build-drivers:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Add MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Configure branding
        run: .\scripts\branding-ci.ps1
        env:
          VENDOR_NAME: ${{vars.VENDOR_NAME}}
          PRODUCT_NAME: ${{vars.PRODUCT_NAME}}
          VENDOR_PREFIX: ${{vars.VENDOR_PREFIX}}
          COPYRIGHT: ${{vars.COPYRIGHT}}
          PackageVersions_Product: ${{vars.PackageVersions_Product}}
          PackageVersions_xenbus: ${{vars.PackageVersions_xenbus}}
          PackageVersions_xencons: ${{vars.PackageVersions_xencons}}
          PackageVersions_xenhid: ${{vars.PackageVersions_xenhid}}
          PackageVersions_xeniface: ${{vars.PackageVersions_xeniface}}
          PackageVersions_xennet: ${{vars.PackageVersions_xennet}}
          PackageVersions_xenvbd: ${{vars.PackageVersions_xenvbd}}
          PackageVersions_xenvif: ${{vars.PackageVersions_xenvif}}
          PackageVersions_xenvkbd: ${{vars.PackageVersions_xenvkbd}}
          PackageVersions_XenClean: ${{vars.PackageVersions_XenClean}}
          PackageVersions_XenBootFix: ${{vars.PackageVersions_XenBootFix}}
          PackageVersions_XenGuestAgent: ${{vars.PackageVersions_XenGuestAgent}}
          MSI_UPGRADE_CODE_X86: ${{vars.MSI_UPGRADE_CODE_X86}}
          MSI_UPGRADE_CODE_X64: ${{vars.MSI_UPGRADE_CODE_X64}}
      - name: Build drivers
        run: .\build-drivers.ps1 -Configuration Release -Platform x64
      - name: Upload artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          path: installer/output/
          name: drivers
    outputs:
      subject-name: drivers
      subject-digest: sha256:${{steps.upload.outputs.artifact-digest}}

  attest-drivers:
    needs: [build-drivers]
    uses: ./.github/workflows/attest.yml
    permissions:
      id-token: write
      contents: read
      attestations: write
    with:
      subject-name: ${{needs.build-drivers.outputs.subject-name}}
      subject-digest: ${{needs.build-drivers.outputs.subject-digest}}

  selfsign-drivers:
    needs: [build-drivers]
    runs-on: windows-latest
    steps:
      # for the sign scripts
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: installer/output/
          name: drivers
      - name: Install certificate
        run: .\scripts\signer-ci.ps1
        env:
          SIGNER_PFX_BASE64: ${{secrets.SIGNER_PFX_BASE64}}
      - name: Sign artifact
        run: |
          . .\scripts\sign.ps1
          Set-SignerFileSignature (Get-ChildItem installer\output -File -Recurse -Include *.sys, *.dll, *.exe, *.cat)
      - name: Clean up certificates
        run: Remove-Item Cert:\CurrentUser\My\* -ErrorAction SilentlyContinue
      - name: Upload artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          path: installer/output/
          name: drivers-signed
