name: build-drivers

on:
  workflow_call:

jobs:
  build-drivers:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Add MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Configure branding
        run: Set-Content -Path branding.ps1 -Value $Env:XCPNG_WINPV_BRANDING -Force
        env:
          XCPNG_WINPV_BRANDING: ${{vars.XCPNG_WINPV_BRANDING}}
      - name: Build drivers
        run: .\build-drivers.ps1 -Configuration Release -Platform x64
      - name: Upload artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          path: installer/output/
          name: drivers
    outputs:
      subject-name: drivers
      subject-digest: sha256:${{steps.upload.outputs.artifact-digest}}

  attest-drivers:
    needs: [build-drivers]
    uses: ./.github/workflows/attest.yml
    permissions:
      id-token: write
      contents: read
      attestations: write
    with:
      subject-name: ${{needs.build-drivers.outputs.subject-name}}
      subject-digest: ${{needs.build-drivers.outputs.subject-digest}}

  selfsign-drivers:
    needs: [build-drivers]
    runs-on: windows-latest
    env:
      SIGNER: ${{vars.XCPNG_WINPV_SIGNER}}
    steps:
      # for the sign scripts
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: installer/output/
          name: drivers
      - name: Install certificate
        run: |
          $pfxBytes = [System.Convert]::FromBase64String($Env:SIGNER_PFX_BASE64)
          $pfxPath = Join-Path $pwd "Signer.pfx"
          [IO.File]::WriteAllBytes($pfxPath, $pfxBytes)
          try {
            certutil -importpfx -f -user -p "" my $pfxPath nochain
            if ($LASTEXITCODE -ne 0) {
                throw "certutil failed with error $LASTEXITCODE"
            }
          } finally {
            Remove-Item -Force $pfxPath
          }
        env:
          SIGNER_PFX_BASE64: ${{secrets.SIGNER_PFX_BASE64}}
      - name: Sign artifact
        run: |
          . .\scripts\sign.ps1
          Set-SignerFileSignature (Get-ChildItem installer\output -File -Recurse -Include *.sys, *.dll, *.exe, *.cat)
      - name: Clean up certificates
        run: Remove-Item Cert:\CurrentUser\My\* -ErrorAction SilentlyContinue
      - name: Upload artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          path: installer/output/
          name: drivers-signed
