name: build-installer

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - Dev
          - Prod
        default: Dev

jobs:
  build-attested:
    uses: ./.github/workflows/build-attested.yml
    with:
      environment: ${{inputs.environment}}
    permissions:
      id-token: write
      contents: read
      attestations: write
    secrets: inherit
  build-installer:
    needs:
      - build-attested
    runs-on: windows-latest
    environment:
      name: ${{inputs.environment}}
      deployment: false
    env:
      # should match up with the WINPV_OUTPUT of each sub-artifact workflow
      DRIVER_EXTRACT: installer/driver-bins
      GUESTAGENT_EXTRACT: xen-guest-agent/target/release
      TIMEPROVIDER_EXTRACT: xentimeprovider/x64/Release
      XSTDVGA_EXTRACT: xstdvga/vs2022/x64/Release/xstdvga
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Download build deps
        run: |
          $ErrorActionPreference = 'Stop'

          New-Item -Type Directory -Path $Env:RUNNER_TEMP/tools/
          Invoke-WebRequest -Uri $Env:SBOM_TOOL_URI -OutFile $Env:RUNNER_TEMP\tools\sbom.exe
          if ((Get-FileHash $Env:RUNNER_TEMP\tools\sbom.exe -Algorithm SHA256).Hash -ine $Env:SBOM_TOOL_SHA256) {
            throw "sbom-tool failed verification"
          }
          Invoke-WebRequest -Uri $Env:SYFT_URI -OutFile $Env:RUNNER_TEMP\tools\syft.zip
          if ((Get-FileHash $Env:RUNNER_TEMP\tools\syft.zip -Algorithm SHA256).Hash -ine $Env:SYFT_SHA256) {
            throw "syft failed verification"
          }
          Expand-Archive $Env:RUNNER_TEMP\tools\syft.zip -DestinationPath $Env:RUNNER_TEMP\tools\syft -Force
          Copy-Item $Env:RUNNER_TEMP\tools\syft\syft.exe $Env:RUNNER_TEMP\tools\syft.exe -Force
          Add-Content -Path $Env:GITHUB_PATH -Value "$Env:RUNNER_TEMP/tools" -Force

          Remove-Item -Path .\deps -Recurse -Force -ErrorAction SilentlyContinue
          Invoke-WebRequest -Uri $Env:WIX_ZIP_URI -OutFile $Env:RUNNER_TEMP\wix.zip
          if ((Get-FileHash $Env:RUNNER_TEMP\wix.zip).Hash -ine $Env:WIX_ZIP_SHA256) {
            throw "wix.zip failed verification"
          }
          Expand-Archive -Path $Env:RUNNER_TEMP\wix.zip -DestinationPath .\deps\wix\ -Force
        env:
          # Dependency download links hardcoded for transparency.
          SBOM_TOOL_URI: https://github.com/microsoft/sbom-tool/releases/download/v4.1.4/sbom-tool-win-x64.exe
          SBOM_TOOL_SHA256: 9ba208cbec21c93b6d1ba01f50681a47d9d14d302f59b33e505b220b89aa0363
          SYFT_URI: https://github.com/anchore/syft/releases/download/v1.38.0/syft_1.38.0_windows_amd64.zip
          SYFT_SHA256: 11a3de4c82b001dae3b69e336f1b89391b676b3e74cead73790c97ff57445941
          WIX_ZIP_URI: https://github.com/xcp-ng/wix-builder/releases/download/v6.0.2-xcpng.1/wix.zip
          WIX_ZIP_SHA256: ccfe8c75f95ea4c4f68a920be827f46c33ce381cc9201a10f565999e3d3b6dd1
      - name: Add MSBuild
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0
      - name: Configure branding
        uses: ./.github/actions/branding
        with:
          branding-data: ${{toJson(vars)}}
      - name: Configure test signer
        run: .\scripts\signer-ci.ps1 -OutFile .\branding.ps1
        env:
          SIGNER_PFX_BASE64: ${{secrets.SIGNER_PFX_BASE64}}
      - name: Download drivers
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: drivers
          path: ${{env.DRIVER_EXTRACT}}/
      - name: Download guestagent
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: guestagent
          path: ${{env.GUESTAGENT_EXTRACT}}/
      - name: Download timeprovider
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: timeprovider
          path: ${{env.TIMEPROVIDER_EXTRACT}}/
      - name: Download xstdvga
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: xstdvga
          path: ${{env.XSTDVGA_EXTRACT}}/
      - name: Testsign all sub-artifacts
        run: |
          $ErrorActionPreference = 'Stop'
          . .\branding.ps1
          . .\scripts\sign.ps1
          Set-SignerFileSignature (Get-ChildItem .\$Env:DRIVER_EXTRACT -File -Recurse -Include *.sys, *.dll, *.exe, *.cat)
          Set-SignerFileSignature (Get-ChildItem .\$Env:GUESTAGENT_EXTRACT -File -Recurse -Include *.dll, *.exe)
          Set-SignerFileSignature (Get-ChildItem .\$Env:TIMEPROVIDER_EXTRACT -File -Recurse -Include *.dll)
          Set-SignerFileSignature (Get-ChildItem .\$Env:XSTDVGA_EXTRACT -File -Recurse -Include *.sys, *.cat)
      - name: Build installer
        id: build
        # this workflow is always testsigned, so -ExportCertificate is appropriate
        run: .\build-installer.ps1 -Configuration Release -Platform x64 -ExportSymbols -ExportExtras -ExportCertificate -Sbom
      - name: Clean up certificates
        if: always()
        run: Remove-Item Cert:\CurrentUser\My\* -ErrorAction SilentlyContinue
      - name: Upload installer
        id: upload
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          path: output/
          name: installer-testsigned
