name: build-timeprovider

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-timeprovider:
    runs-on: windows-latest
    env:
      WINPV_OUTPUT: xentimeprovider/x64/Release
      WINPV_CATALOG: catalog.csv
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
      - name: Add MSBuild
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0
      - name: Configure branding
        uses: ./.github/actions/branding
        with:
          branding-data: ${{toJson(vars)}}
      - name: Build time provider
        run: .\build-timeprovider.ps1 -Configuration Release -Platform x64
      - name: Catalog time provider
        run: |
          Import-Module .\scripts\artifact.psm1 -Force
          Get-ArtifactCatalog -Path .\$Env:WINPV_OUTPUT -Include *.dll |
          Export-Csv -NoTypeInformation .\$Env:WINPV_OUTPUT\$Env:WINPV_CATALOG
      - name: Upload time provider
        id: upload
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: timeprovider
          path: ${{env.WINPV_OUTPUT}}/
    outputs:
      output-path: ${{env.WINPV_OUTPUT}}
      output-sha256: ${{steps.upload.outputs.artifact-digest}}
      catalog-name: ${{env.WINPV_CATALOG}}
