name: build-xstdvga

on:
  workflow_call:
    inputs:
      environment:
        type: string
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - Dev
          - Prod
        default: Dev

jobs:
  build-xstdvga:
    runs-on: windows-2022
    environment:
      name: ${{inputs.environment}}
      deployment: false
    env:
      WINPV_OUTPUT: xstdvga/vs2022/x64/Release/xstdvga
      WINPV_CATALOG: catalog.csv
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: true
      - name: Add MSBuild
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0
      - name: Add CodeQL
        run: |
          $ErrorActionPreference = 'Stop'
          New-Item -Type Directory -Path $Env:RUNNER_TEMP/tools/
          Invoke-WebRequest -Uri $Env:CODEQL_URI -OutFile $Env:RUNNER_TEMP\tools\codeql.zip
          if ((Get-FileHash $Env:RUNNER_TEMP\tools\codeql.zip -Algorithm SHA256).Hash -ine $Env:CODEQL_SHA256) {
            throw "codeql failed verification"
          }
          Expand-Archive $Env:RUNNER_TEMP\tools\codeql.zip -DestinationPath $Env:RUNNER_TEMP\tools\codeql -Force
          Add-Content -Path $Env:GITHUB_PATH -Value "$Env:RUNNER_TEMP\tools\codeql\codeql" -Force
        env:
          CODEQL_URI: https://github.com/github/codeql-cli-binaries/releases/download/v2.25.5/codeql-win64.zip
          CODEQL_SHA256: db470e09a5f94e9d262f0e1a67af1ff1c72571d567898d3a44c4b09c581afc6e
      - name: Download packs
        run: |
          codeql pack download microsoft/windows-drivers@1.10.0 microsoft/cpp-queries@0.0.5
          if ($LASTEXITCODE -ne 0) {
            throw "CodeQL download failed with error $LASTEXITCODE"
          }
      - name: Configure branding
        uses: ./.github/actions/branding
        with:
          branding-data: ${{toJson(vars)}}
      - name: Build xstdvga
        run: .\build-xstdvga.ps1 -Configuration Release -Platform x64
      - name: Catalog xstdvga
        run: |
          Import-Module .\scripts\artifact.psm1 -Force
          Get-ArtifactCatalog -Path .\$Env:WINPV_OUTPUT -Include *.sys, *.inf |
          Export-Csv -NoTypeInformation .\$Env:WINPV_OUTPUT\$Env:WINPV_CATALOG
      - name: Upload xstdvga
        id: upload
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: ${{env.WINPV_OUTPUT}}/
          name: xstdvga
    outputs:
      output-path: ${{env.WINPV_OUTPUT}}
      output-sha256: ${{steps.upload.outputs.artifact-digest}}
      catalog-name: ${{env.WINPV_CATALOG}}
