name: test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: false
          persist-credentials: false
      - uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: "10.0.x"
      - name: Add branding
        run: New-Item -Type File -Path branding.ps1 -Value '$Env:VENDOR_PREFIX = "XN"'
      - name: InstallerTests
        run: |
          foreach ($Configuration in @("Debug", "Release")) {
            dotnet run `
              --project InstallerTests\InstallerTests.csproj `
              --configuration $Configuration `
              --property:Platform=x64
            if ($LASTEXITCODE -ne 0) {
              throw "InstallerTests failed with error $LASTEXITCODE"
            }
          }
      - name: xenplus_tests
        run: |
          foreach ($Configuration in @("Debug", "Release")) {
            dotnet run `
              --project xenplus_tests\xenplus_tests.csproj `
              --configuration $Configuration `
              --property:Platform=x64
            if ($LASTEXITCODE -ne 0) {
              throw "xenplus_tests failed with error $LASTEXITCODE"
            }
          }
