name: test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: false
          persist-credentials: false
      - uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: "10.0.x"
      - name: Add branding
        run: New-Item -Type File -Path branding.ps1 -Value '$Env:VENDOR_KEY = "XCP-ng"; $Env:VENDOR_PREFIX = "XN"; $PackageVersions = @{ Product = "9.1.0.0" }; $Env:MSI_UPGRADE_CODE_X86 = "{10828840-D8A9-4953-B44A-1F1D3CD7ECB0}"; $Env:MSI_UPGRADE_CODE_X64 = "{D60FED1E-316C-41B0-B7A5-E44951A82618}"'
      - name: InstallerTests
        run: |
          foreach ($Configuration in @("Debug", "Release")) {
            dotnet run `
              --project InstallerTests\InstallerTests.csproj `
              --configuration $Configuration `
              --property:Platform=x64
            if ($LASTEXITCODE -ne 0) {
              throw "InstallerTests failed with error $LASTEXITCODE"
            }
          }
      - name: xenplus_tests
        run: |
          foreach ($Configuration in @("Debug", "Release")) {
            dotnet run `
              --project xenplus_tests\xenplus_tests.csproj `
              --configuration $Configuration `
              --property:Platform=x64
            if ($LASTEXITCODE -ne 0) {
              throw "xenplus_tests failed with error $LASTEXITCODE"
            }
          }
